# Configuración de la API de WhatsApp
# Ejemplo:
# WHATSAPP_API_URL = "https://api.tuwhatsapp.com/send"
# WHATSAPP_API_TOKEN = "tu_token_secreto"
# """
# Django settings for cheater project.
#
# Generated by 'django-admin startproject' using Django 5.2.1.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """
#
# from pathlib import Path
# import os
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-1^pagal2tm&(yhx+!$^)60q*2y2a$e6-5m&_hxc-@as2+8@s3_"
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = [
#     "localhost",
#     "104.248.177.44",
#     "206.189.223.102",
#     "127.0.0.1",
#     os.environ.get("RAILWAY_STATIC_URL", ""),
#     os.environ.get("RAILWAY_PUBLIC_DOMAIN", ""),
#     "web-production-064ec.up.railway.app",
#     ".feuoir.com",
#     "www.feuoir.com",
#     "web-production-d583.up.railway.app"
# ]
# # Application definition
#
# INSTALLED_APPS = [
#     "unfold",
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",
#     "corsheaders",
#     "ciscoapp",
# ]
#
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "whitenoise.middleware.WhiteNoiseMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "corsheaders.middleware.CorsMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]
#
# ROOT_URLCONF = "cheater.urls"
#
# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [BASE_DIR / 'templates'],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]
#
# WSGI_APPLICATION = "cheater.wsgi.application"
#
#
# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'cisco_cheater',
# #         'USER': 'admin',
# #         'PASSWORD': 'FqDcuEmkZn86bFzcV9j1J1jTtgBnYXU6',
# #         'HOST': 'dpg-d156nme3jp1c73fhistg-a',
# #         'PORT': '5432',
# #     }
# # }
#
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',  # Default path for SQLite DB
# #     }
# # }
#
# # import dj_database_url
# #
# # DATABASES = {
# #     'default': dj_database_url.config(default='sqlite:///db.sqlite3')
# # }
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'railway',
#         'USER': 'postgres',
#         'PASSWORD': 'uTqosJfPREVyCHBerXjflrKaNFPCoFaB',
#         'HOST': 'switchyard.proxy.rlwy.net',
#         'PORT': '27212',
#     }
# }
#
# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.postgresql',
# #         'NAME': 'cisco_cheater_2',       # Nombre de tu base de datos local
# #         'USER': 'postgres',               # Usuario de PostgreSQL que creaste
# #         'PASSWORD': '12345',           # Contraseña sencilla (solo para uso local)
# #         'HOST': 'localhost',           # 'localhost' si es una instalación local
# #         'PORT': '5432',                # Puerto por defecto de PostgreSQL
# #     }
# # }
#
# # import os
# # import dj_database_url
# #
# # DATABASES = {
# #     'default': dj_database_url.config(
# #         default=os.environ.get('DATABASE_URL', 'postgresql://postgres:OkYqAtgdhWOKYkavUQHlgvXqtqMUiRZC@postgres.railway.internal:5432/railway'),
# #         conn_max_age=600,
# #         ssl_require=True
# #     )
# # }
#
#
# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]
#
#
# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/
#
# LANGUAGE_CODE = "en-us"
#
# TIME_ZONE = 'America/Guayaquil'  # o 'America/Bogota'
#
# USE_I18N = True
#
# USE_TZ = True
#
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/
#
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_DIRS = [
#     BASE_DIR / 'static',
# ]
#
# # Configuración para servir archivos estáticos en producción
# if not DEBUG:
#     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#
# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
#
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:8000",
#     "http://127.0.0.1:8000",
#     "https://cisco-cheater.onrender.com",
#     "https://web-production-064ec.up.railway.app",
#     "https://web-production-0481a.up.railway.app",
#     "https://feuoir.com",
#     "https://web-production-d583.up.railway.app"
# ]
#
# CORS_ALLOWED_METHODS = [
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# ]
#
# CORS_ALLOWED_HEADERS = [
#     "accept",
#     "accept-encoding",
#     "authorization",
#     "content-type",
#     "dnt",
#     "origin",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# ]
#
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
#
# # Si quieres permitir admin desde cualquier origen (solo testing)
# CSRF_TRUSTED_ORIGINS = [
#     "https://web-production-d583.up.railway.app"
# ]
#
# DEBUG = False
# ALLOWED_HOSTS = ["web-production-d583.up.railway.app"]
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
# CSRF_TRUSTED_ORIGINS = ["https://*.railway.app"]
# CSRF_ALLOWED_ORIGINS = ["https://web-production-d583.up.railway.app"]

"""
Django settings for cheater project (producción Railway).
"""

import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# -------------------------
# Paths
# -------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

import sys
BUILDING_STATIC = "collectstatic" in sys.argv


def _env_list(name: str, default: str) -> list[str]:
    raw = os.environ.get(name, default)
    return [x.strip() for x in raw.split(",") if x.strip()]


# -------------------------
# Security
# -------------------------
SECRET_KEY = os.environ.get("SECRET_KEY", "").strip()
if not SECRET_KEY:
    if BUILDING_STATIC:
        SECRET_KEY = "dummy-build-key-for-collectstatic"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY is not set. Copy .env.example to .env and assign a unique value."
        )

DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = _env_list(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1,.railway.app,.up.railway.app",
)
for _env_key in ("RAILWAY_PUBLIC_DOMAIN", "RAILWAY_STATIC_URL"):
    _raw = os.environ.get(_env_key, "").strip()
    if not _raw:
        continue
    _host = urlparse(_raw).hostname if "://" in _raw else _raw.split("/")[0]
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

if os.environ.get("USE_X_FORWARDED_PROTO", "").lower() in ("true", "1", "yes"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# -------------------------
# Applications
# -------------------------
INSTALLED_APPS = [
    "unfold",
    "ciscoapp",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "corsheaders",
]

# -------------------------
# Middleware
# -------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cheater.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cheater.wsgi.application"

# -------------------------
# Database (PostgreSQL; Trigram search requires it)
# -------------------------
db_url = os.environ.get("DATABASE_URL", "").strip()
if not db_url:
    if BUILDING_STATIC:
        db_url = "sqlite:///:memory:"
    else:
        raise ImproperlyConfigured(
            "DATABASE_URL is not set. Use .env locally; Railway/Render set it automatically."
        )

DATABASE_SSL_REQUIRE = os.environ.get("DATABASE_SSL_REQUIRE", "").lower() in (
    "true",
    "1",
    "yes",
)

DATABASES = {
    "default": dj_database_url.parse(
        db_url,
        conn_max_age=600,
        ssl_require=DATABASE_SSL_REQUIRE,
    )
}

# -------------------------
# Password validation
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------
# Internationalization
# -------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Guayaquil"
USE_I18N = True
USE_TZ = True

# -------------------------
# Static files
# -------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------
# CORS configuration
# -------------------------
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = _env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000",
)
# Add Railway domain automatically
for _env_key in ("RAILWAY_PUBLIC_DOMAIN",):
    _d = os.environ.get(_env_key, "").strip()
    if _d:
        _cors_origin = _d if _d.startswith("http") else f"https://{_d}"
        if _cors_origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_cors_origin)

# Allow all chrome-extension:// origins (for the extension)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^chrome-extension://.*$",
    r"^https://.*\.netacad\.com$",
    r"^https://.*\.netacad\.net$",
    r"^https://.*\.cisco\.com$",
]
CORS_ALLOWED_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]
CORS_ALLOWED_HEADERS = [
    "accept", "accept-encoding", "authorization", "content-type",
    "dnt", "origin", "user-agent", "x-csrftoken", "x-requested-with",
]

# -------------------------
# CSRF / Cookie security
# -------------------------
CSRF_TRUSTED_ORIGINS = _env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:8000,http://127.0.0.1:8000",
)
for _env_key in ("RAILWAY_PUBLIC_DOMAIN",):
    _d = os.environ.get(_env_key, "").strip()
    if _d:
        _origin = _d if _d.startswith("http") else f"https://{_d}"
        if _origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_origin)

_default_secure = str(not DEBUG).lower()
CSRF_COOKIE_SECURE = os.environ.get("CSRF_COOKIE_SECURE", _default_secure).lower() in (
    "true",
    "1",
    "yes",
)
SESSION_COOKIE_SECURE = os.environ.get(
    "SESSION_COOKIE_SECURE", _default_secure
).lower() in ("true", "1", "yes")

# -------------------------
# Default primary key
# -------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static

UNFOLD = {
    "SITE_TITLE": "cisco-cheater admin",
    "SITE_HEADER": "cisco cheater",
    "SITE_SUBHEADER": "renata xd",
    "SITE_URL": "/",
    "SITE_SYMBOL": "bolt",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": False,
    "THEME": "light",  # Tema claro
    "BORDER_RADIUS": "8px",
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#3b82f6",
            "600": "#2563eb",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        },
        "base": {
            "50": "#f8fafc",
            "100": "#f1f5f9",
            "200": "#e2e8f0",
            "300": "#cbd5e1",
            "400": "#94a3b8",
            "500": "#64748b",
            "600": "#475569",
            "700": "#334155",
            "800": "#1e293b",
            "900": "#0f172a",
            "950": "#020617",
        },
        "font": {
            "subtle-light": "var(--color-base-600)",
            "subtle-dark": "var(--color-base-400)",
            "default-light": "var(--color-base-700)",
            "default-dark": "var(--color-base-300)",
            "important-light": "var(--color-base-900)",
            "important-dark": "var(--color-base-100)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Dashboard"),
                "separator": True,
                "items": [
                    {
                        "title": _("Overview"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": _("Exámenes"),
                "separator": True,
                "items": [
                    {
                        "title": _("Exámenes"),
                        "icon": "school",
                        "link": reverse_lazy("admin:ciscoapp_exam_changelist"),
                    },
                    {
                        "title": _("Preguntas"),
                        "icon": "quiz",
                        "link": reverse_lazy("admin:ciscoapp_question_changelist"),
                    },
                    {
                        "title": _("Respuestas"),
                        "icon": "check_circle",
                        "link": reverse_lazy("admin:ciscoapp_answer_changelist"),
                    },
                    {
                        "title": _("Scrapear Examen"),
                        "icon": "download",
                        "link": reverse_lazy("admin:ciscoapp_exam_scrape"),
                    },
                ],
            },
            {
                "title": _("Activation Keys"),
                "separator": True,
                "items": [
                    {
                        "title": _("All Keys"),
                        "icon": "key",
                        "link": reverse_lazy("admin:ciscoapp_activationkey_changelist"),
                    },
                ],
            },
            {
                "title": _("User Management"),
                "separator": True,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": _("Groups"),
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
            {
                "title": _("Site"),
                "separator": True,
                "items": [
                    {
                        "title": _("Home Page"),
                        "icon": "home",
                        "link": "/",
                    },
                ],
            },
        ],
    },
    "LOGIN": {
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "STYLES": [
        lambda request: static("admin/custom.css"),
    ],
}

